### ISSUE TITLE
This bundle won't work on Mac OS X 10.11.3 with Mathematica 10.4

### ISSUE THREAD

**Issue by sunt05** [dehowell/mathematica-tmbundle#11]
Please modify the 'mathmate.py' script:
in line 150 of mathmate.py:
`classpath.append("/Applications/Mathematica.app/SystemFiles/Links/JLink/JLink.jar")` 
the path is incorrect, which should be modified as follows:
`classpath.append("/Applications/Mathematica.app/SystemFiles/Contents/Links/JLink/JLink.jar")`.

**Comment by dehowell** [comment]
Good catch. I'm not personally using Mathematica or TextMate much these days and I'm wondering how often the path of `JLink.jar` in the application bundle has changed. I've updated the package to point to the location on my own system (Mac OS X 10.11.3 with Mathematica 10.0), but that may not be the most robust fix for the problem.

A better fix would probably be to for `mathmate.py` to search `/Applications/Mathematica.app/` for `JLink.jar` instead of hardcoding a location. If you'd like to make a pull request, I'd be happy to look at it. But I'm afraid that I don't have much personal development time and this bundle isn't high on my priority list.

**Comment by sunt05** [comment]
I fully agree with your approach.
However, due to my very limited expertise in Python programming, I'm afraid I cannot finish it soon.
So for the being, it's better to write it down here and I may get back to this sometime in the future.

Also, thanks very much for your bundle, which helped me a lot!

**Comment by dehowell** [comment]
I had a few minutes more to look at this tonight, so I called the `find` command from `mathmate.py` to locate `JLink.jar`, so that ought to be a little sturdier of a solution. Thanks for reporting the issue!
